# Site settings
title: Ben Pullman
email: bp2@icloud.com
description: Ben Pullman's Personal Website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://benpullman.com" # the base hostname & protocol for your site
twitter_username: benpullman
github_username:  benpullman

pages: ./_pages
# Build settings
markdown: kramdown